///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesChatLogo = 'assets/images/app_logo.png';
  static const String imagesOpenaiLogo = 'assets/images/app_logo.jpg';
  static const String imagesPerson = 'assets/images/person.jpeg';
  static const String jsonLanguages = 'assets/json/languages.json';

}
